# .hadolint.yml - Hadolint configuration
#
# Documentation:
# - https://github.com/hadolint/hadolint#configure
#
failure-threshold: warning
ignored:
- DL3003  # Use WORKDIR to switch to a directory.
- DL3008  # Pin versions in apt-get install.
- DL4006  # Set the SHELL option -o pipefail before RUN with a pipe in it.
- SC2086  # Double quote to prevent globbing and word splitting.
label-schema:  # https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys
  org.opencontainers.image.title: text
  org.opencontainers.image.description: text
  org.opencontainers.image.version: semver
  org.opencontainers.image.licenses: spdx
  org.opencontainers.image.authors: text
  org.opencontainers.image.vendor: text
  maintainer: text
strict-labels: true
trustedRegistries:
- docker.io
- ghcr.io
- registry.gitlab.com
- mcr.microsoft.com
