name: Python wheel

on:
  push:
    branches:
    - master

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: |
            3.8
            3.9
            3.10
            3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install nox
    - name: Lint with Ruff
      run: nox --sessions lint
    - name: Test with pytest
      run: nox --sessions test
    - name: Build Python wheel
      run: nox --sessions build
    - name: Archive Python wheel
      uses: actions/upload-artifact@v3
      with:
        name: random_xml_csv
        path: dist/*.whl
